### ISSUE TITLE
Add a TestSoma.hoc creating a single comp cell with channels in NEURON & add OMV tests

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell#12]
To establish a baseline of what a soma with the core set of channels should do. Base it on soma in the real cell
See for example https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/NMC/NEURON/Test_Soma.hoc
https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/NMC/NEURON/.test.nrn.omt

Add to https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/tree/master/NEURON/test to keep top level files same as ModelDB originals

**Comment by shayanshafquat** [comment]
@pgleeson 

1. It throws nan values when I try loading the hoc file. I'm still figuring out what's wrong with my understanding.
2. The target value in the .omt test file is path? Is there any documentation on how to create the omt test files.

**Comment by shayanshafquat** [comment]
But I am unable to see plots locally. The code is failing to load the neuron GUI. So, still not sure whether the simulation is getting the required results.

**Comment by shayanshafquat** [comment]
How to create .test.mep file? Suppose we want to analyze the spike times? How do we get to know about the ground truth spike timing? I referred the paper too but was not able to find any useful information.
