### ISSUE TITLE
Add test hoc/python script to load full cell from example 1 & save results to file & add OMV test

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell#13]
Along the lines of https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/NMC/NEURON/Test_L1.hoc
Again best in https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/tree/master/NEURON/test.

**Comment by pgleeson** [comment]
@shayan823 When you start testing on the full cell, what I'd recommend is leaving the existing scripts/tests in place for the single compartment cell and just append these files to allow for testing/genertaing networks with the full cell (e.g. make cell.py modular so it can geenrate either)

**Comment by shayanshafquat** [comment]
I have added the current version of the entire cell in NeuroML. I need help with regards to following: @pgleeson 

1. In [kca.mod](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/8cdfe0da312e73fb96c2c6657efcd711474b8ced/NEURON/channels/kca.mod#L22-L23) we see a mention of two ions, then what should be mentioned in the ion tag when declaring in NeuroML?
2. I was going through the documentation pages but wasnt able to find how to incorporate apical axial resistance into the model?
3. To add [cad.nml](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/issue_13_test/NeuroML2/cad.nml) into the intracellularProperties where we need to mention InitialExtConcentration and initialConcentration [as here](https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/2cd8aa77342576c1a871f5d500d791f927444913/NMC/NeuroML2/bNAC219_L1_DAC_a9ae5cbbf5_0_0.cell.nml#L5333-L5334).
4. How do we interpret mnat and mih mentioned [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/8cdfe0da312e73fb96c2c6657efcd711474b8ced/NEURON/reduced_model.hoc#L105-L109) for calculating conductance for apical nat and ih channels. For tuft, I have used conductance density mentioned in this [file](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/8cdfe0da312e73fb96c2c6657efcd711474b8ced/NEURON/init_models_with_ca/init_model2.hoc#L14-L15).


Meanwhile, I will be validating the following now:

1. To add sca and kca density mechanisms, I have used ChanneldensityNernst, hoping that it be correct.
2. The way I am calculating the distance from the soma for segment groups apicaltree_list and apical.
3. Adding vshift for channel nat using channeldensityvshift.

**Comment by pgleeson** [comment]
@shayan823 

> 1. In [kca.mod](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/8cdfe0da312e73fb96c2c6657efcd711474b8ced/NEURON/channels/kca.mod#L22-L23) we see a mention of two ions, then what should be mentioned in the ion tag when declaring in NeuroML?

Since it's a K transmitting channel, use the k as the ion here. The Ca dependence comes in when you use an element like: https://docs.neuroml.org/Userdocs/Schemas/Channels.html#basevoltageconcdeptime, see under the Requirements tab.

>  2. I was going through the documentation pages but wasnt able to find how to incorporate apical axial resistance into the model?
> 

In the same way that you can add segmentGroup in channelDensity and specificCapacitance, see:
https://raw.githubusercontent.com/OpenSourceBrain/PurkinjeCell/master/neuroConstruct/generatedNeuroML2/purk2.cell.nml

you should be able to use something like `<resistivity segmentGroup="apical_group" value="0.25 kohm_cm"/>`

**Comment by pgleeson** [comment]
>  3. To add [cad.nml](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/issue_13_test/NeuroML2/cad.nml) into the intracellularProperties where we need to mention InitialExtConcentration and initialConcentration [as here](https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/2cd8aa77342576c1a871f5d500d791f927444913/NMC/NeuroML2/bNAC219_L1_DAC_a9ae5cbbf5_0_0.cell.nml#L5333-L5334).
> 

Not sure what the question is here... Is it how do you get the values for these? The easiest way is to run the original NEURON code and check cai (internal) and cao (external)

>  4. How do we interpret mnat and mih mentioned [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/8cdfe0da312e73fb96c2c6657efcd711474b8ced/NEURON/reduced_model.hoc#L105-L109) for calculating conductance for apical nat and ih channels. For tuft, I have used conductance density mentioned in this [file](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/8cdfe0da312e73fb96c2c6657efcd711474b8ced/NEURON/init_models_with_ca/init_model2.hoc#L14-L15).
> 

I believe `tuft mih = gbar_ih/distance(0)` means: select the segment tuft and give me the value of gbar_ih there, and then divide that by the distance (from the soma) to the 0th point of tuft, and the value of the division set to mih. So basically calculating soem normalisation constant, so that the gbar_ih(x) below produces a value of gbar_ih when it hits the start of the tuft.
> 
> Meanwhile, I will be validating the following now:
> 
>     1. To add sca and kca density mechanisms, I have used ChanneldensityNernst, hoping that it be correct.
> 
>     2. The way I am calculating the distance from the soma for segment groups apicaltree_list and apical.
> 
>     3. Adding vshift for channel nat using channeldensityvshift.

What would be good before continuing too far with the multicomp cell, would be to create a (new) test cell in Neuron and NeuroML, which has just the soma but adds the Ca pool, then the ca channel, then the kca channel, and compares to Nrn to Nml. It might be good to create a new branch, and merge work to date to master as there are useful updates to the plots etc. in here.

**Comment by shayanshafquat** [comment]
I first added cad and sca channels, plotted the activation/inactivation variables, and compared the results. Both being the same, I tried adding the kca channel but was unable to understand which channel density mechanism fits here best.

As it has two ions, it reads ek, cai both but using channeldensity as [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/a6a8514ca6dcaa88dd7ce1b1b94b72ee6502e0b4/NeuroML2/pyr_ca_cell.nml#L18) leaves no scope to add information related to ca. I searched for examples too but unable to find them.

Apart from that, how to add information related to eca as in [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/a6a8514ca6dcaa88dd7ce1b1b94b72ee6502e0b4/NEURON/channels/Test_ca_soma.hoc#L21) into NeuroML code.
 @pgleeson

**Comment by pgleeson** [comment]
@shayan823 For the kca it's best to ignore ca inside here and just assume what it's getting from outside (and using in its equations) is correct. What you're interested in here is the activation variable n, the conductace g that leads to, and the current it gives to the cell, which is a potassium current.

For NeuroML, plotting/saving these should be no different from another potassium channel.

<img width="802" alt="Screenshot 2022-08-02 at 16 54 47" src="https://user-images.githubusercontent.com/1556687/182419244-54e54b63-ce50-4902-b211-764e110fd742.png">

**Comment by shayanshafquat** [comment]
I checked the plots for the n activation variable but it's not matching to the above (NEURON). 


1. Wanted to check the plots for cai, cao, ica and eca using NeuroML using this [notebook](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/ca_pool_tests/NeuroML2/test_ca/soma_ca.ipynb) as I did in NEURON [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/7bf14cf261896ee9f385abd6f6e769629df0be5e/NEURON/channels/Test_ca_soma.hoc#L92-L95). Where does it get recorded? 
2. Is there any documentation which can help me understand the functionalities of the tags (like OnStart, OnCondition) as in the cad file [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/7bf14cf261896ee9f385abd6f6e769629df0be5e/NeuroML2/cad.nml#L52). How to be sure that I have converted the cad channel to NeuroML correctly? 

3. For the sca channel I'm currently using ChannelDensityGHK2 module as shown [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/7bf14cf261896ee9f385abd6f6e769629df0be5e/NeuroML2/test_ca/pyr_ca_cell.nml#L18-L19). It gave me desired plots in terms of the m,h activation variables. I am confused if there are supposed to be any other reasons that can help me choose that.

@pgleeson

**Comment by shayanshafquat** [comment]
Is there a way to save the output of gbar (condDensity) for a specific segment group something like this `simulation.add_column_to_output_file("output2", column_id="pop0_cond_kslow_soma", quantity="pop0/0/pyr/0/biophys/membraneProperties/kslow_soma/gDensity")`. I tried condDensity instead of gDensity but it  fails. @pgleeson 

As I was trying to add non uniform channels, was trying to set the cond_sensity to be the same as variable parameter. I tried doing using `pynml-summary *.net.nml` but I think it only supports the base structure of channel density and fails to show information for components like ChannelDensityVShift / ChannelDensityNonUniform.

**Comment by pgleeson** [comment]
@shayan823 Just checking whether I covered this in the meeting on Friday..? I believe all that can be plotted (via LEMS) is the value of gDensity at the centre of any segment known to NML. However, if you load it in Neuron, you can list and plot any value at any point in its sections.

**Comment by shayanshafquat** [comment]
Yeah, we covered that.
I was trying to add vshift2 to nat for the segment "iseg". Adding that as a requirement in nml file is done, but facing issues with passing the value of vshift2 using python modules like channelDensity / channelDensityVshift as **kwargs. After this I can raise a PR for this issue as all the other channels have been added and are matching nicely. @pgleeson
