### ISSUE TITLE
Move parse_mod_file.py  to better place

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell#15]
The utility script https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/master/parse_mod_file.py would be useful for multiple projects. 

It could be moved to a better place (pyNeuroML say, in [here](https://github.com/NeuroML/pyNeuroML/tree/master/pyneuroml/neuron)) and usage documented here: https://docs.neuroml.org/Userdocs/Software/Tools/NEURON.html

**Comment by shayanshafquat** [comment]
Actually, I exported it from [there](https://github.com/NeuroML/pyNeuroML/tree/master/pyneuroml/neuron/mod) only to help generate a basic template of the channels to be converted to NeuroML.

**Comment by shayanshafquat** [comment]
I have moved the files to https://github.com/OpenSourceBrain/NEURONShowcase and opened a PR for it there. @pgleeson

**Comment by pgleeson** [comment]
Thanks!
