### ISSUE TITLE
Add axon_group, dend_group & soma_group to generated nml cells

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell#31]
See https://docs.neuroml.org/Userdocs/Conventions.html#neuron-segments. Will ease visualisation of the cells

**Comment by shayanshafquat** [comment]
@pgleeson The warning was raised even for `axon_0` when included in `axon_group`. Probably then the member segments of _(hillock, iseg)_ not getting reflected in the `axon_group` have nothing to do with the warning statements. On top of that, I tried reordering the segment group definitions but it didn't help and that may be because of two reasons:

- `axon_group`, `dendrite_group`, `soma_group` are initialised inside `cellBuilder` in the `create_cell()` method before I get to define hillock, iseg or other segments
- It's still able to recognise soma_0, axon_0 so maybe it checks for segments with prefixes` soma_ `, `axon_`,  `dend_` in the nml file but not for other segments

Attached is the output for `pynml -validate` when run on the recent `pyr.cell.nml`.
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/16141677/188132864-992fcc9a-3277-4088-8215-6a2872c3cfb8.png">

**Comment by pgleeson** [comment]
You could restructure your own code to fix all this, but since it may well come up for other people's models , how about making a helper method in pyneuroml which accepts in a cell, and reorders the list in `cell.morphology.segment_groups`  to put all the seg groups with no included groups first, then adds the rest making sure any group they refer to are already in the list (and throws an informative error if finds anythign funny)...

It could be a standalone method `reorder_segment_groups(cell)` in https://github.com/NeuroML/pyNeuroML/blob/development/pyneuroml/utils/CellBuilder.py, which can be called on its own or as part of the processof building a cell with the CellBuilder.

**Comment by shayanshafquat** [comment]
Restructuring it shows no warning. But, that won't overcome the issue of the member segments getting reflected in the segment groups `soma_group`, `axon_group`, and `dendrite_group`. Though it may solve some of the discrepancies while converting the nml cell file to neuron.

**Comment by pgleeson** [comment]
@shayan823 Also try `pynml-summary pyr.cell.nml -v` it will contain a summary of what it reads from the file including about segment groups, e.g.
```
...
*  
*    SegmentGroup: all,	27 member(s),	0 included group(s);	contains 27 segments in total
*    SegmentGroup: soma_group,	2 member(s),	1 included group(s);	contains 2 segments in total
*    SegmentGroup: axon_group,	2 member(s),	3 included group(s);	contains 14 segments in total
*    SegmentGroup: dendrite_group,	0 member(s),	3 included group(s);	contains 11 segments in total
*    SegmentGroup: soma_0,	2 member(s),	0 included group(s);	contains 2 segments in total
*    SegmentGroup: hillock_0,	6 member(s),	0 included group(s);	contains 6 segments in total
*    SegmentGroup: basal_0,	2 member(s),	0 included group(s);	contains 2 segments in total
*    SegmentGroup: apical_0,	6 member(s),	0 included group(s);	contains 6 segments in total
*    SegmentGroup: iseg_0,	6 member(s),	0 included group(s);	contains 6 segments in total
*    SegmentGroup: tuft_0,	3 member(s),	0 included group(s);	contains 3 segments in total
*    SegmentGroup: axon_0,	2 member(s),	0 included group(s);	contains 2 segments in total
*    SegmentGroup: basal_group,	0 member(s),	1 included group(s);	contains 2 segments in total
*    SegmentGroup: apical_group,	0 member(s),	1 included group(s);	contains 6 segments in total
*    SegmentGroup: tuft_group,	0 member(s),	1 included group(s);	contains 3 segments in total
*    SegmentGroup: hillock_group,	0 member(s),	1 included group(s);	contains 6 segments in total
*    SegmentGroup: iseg_group,	0 member(s),	1 included group(s);	contains 6 segments in total
*    SegmentGroup: axosomatic_list,	0 member(s),	5 included group(s);	contains 18 segments in total
*    SegmentGroup: apicaltree_list,	0 member(s),	2 included group(s);	contains 9 segments in total
...
```


Also, I see from pyr.cell.nml that you include the segments themselves as well as the defined seg groups, which is not required:

```
  <segmentGroup neuroLexId="GO:0043025" id="soma_group">
                <notes>Default soma segment group for the cell</notes>
                <property tag="color" value="0 0 0.8"/>
                <member segment="0"/>
                <member segment="1"/>
                <include segmentGroup="soma_0"/>
            </segmentGroup>
            <segmentGroup neuroLexId="GO:0030424" id="axon_group">
                <notes>Default axon segment group for the cell</notes>
                <property tag="color" value="0 0.8 0"/>
                <member segment="25"/>
                <member segment="26"/>
                <include segmentGroup="axon_0"/>
                <include segmentGroup="hillock_0"/>
                <include segmentGroup="iseg_0"/>
            </segmentGroup>

```
Just do one of the other...

**Comment by shayanshafquat** [comment]
What is the difference between the count of members and segments? I expect both to be equal for each of the defined segment groups.

Do you mean adding segment groups like `basal_group`, `apical_group`,`hillock_group` on top of adding segments like `basal_0` , `apical_0`, `hillock_0`. I did that when adding channel densities to these segments (let's say `basal_0`) throws error whereas including them to defined segment groups solves that. Maybe it has something to do with the naming of the segments is what we discussed.

**Comment by pgleeson** [comment]
> What is the difference between the count of members and segments? I expect both to be equal for each of the defined segment groups.
> 

The first 2 counts are the explicit `<member>` and `<include>` subelements, then in works out what segments are in each of these and gives the (nonoverlapping) total of actual segments. 

> Do you mean adding segment groups like `basal_group`, `apical_group`,`hillock_group` on top of adding segments like `basal_0` , `apical_0`, `hillock_0`. I did that when adding channel densities to these segments (let's say `basal_0`) throws error whereas including them to defined segment groups solves that. Maybe it has something to do with the naming of the segments is what we discussed.

Be careful about the difference between these. There is no segment named `basal_0`. Segments should only be referenced by their integer ids. You define the group soma_0 as containing sements 0 and 1, and then define soma_group as containing 0 and 1 **as well as** soma_0 which is redundant.

Note there is no problem having both groups `basal_0` and `basal_group` and then being identical, one or the other might be better/clearer for use in channel density definitions. 
Note too that the `neuroLexId="sao864921383"` says "map this to a Neuron section" and I think channel densities can only point to **groups of** segment groups which are Neuron sections, rather than pure Neuron sections. 
This is connected together a lot better when the nml file is exported from Neuron itself...
