### ISSUE TITLE
NEURON tests failing: Error compiling mod files

### ISSUE THREAD

**Issue by shayanshafquat** [OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell#38]
https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/runs/7888936356?check_suite_focus=true#step:5:79 @pgleeson

**Comment by pgleeson** [comment]
Not sure if it's the real reason, but I noticed you have multiple changes to the original hoc/mod files committed on your branch, see https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/compare/master...multi_comp_tests

You can change these locally for testing, but the original files should stay as is. I think the change in [NEURON/channels/nat.mod](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/compare/master...multi_comp_tests#diff-5d18c18d3cb8d539e5bcd97f6da080030a459378c5a82ca2b9ded5f90d55e7e7) at least is causing issues

**Comment by shayanshafquat** [comment]
I did not change anything in the master repo so I expected it to be running fine here seeing it passing all the tests I merged it but from then it fails which is weird. 

And yes, I will make sure I don't commit the changes in hoc/mod files.

**Comment by shayanshafquat** [comment]
Closing this as it has been resolved after reverting back to original hoc/mod file.
