### ISSUE TITLE
Create an instructional notebook to load models and change input values as in paper

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell#44]
It would be great to have a simple Jupyter notebook which just loaded the NML model and put in some simple inputs as done in the paper and plot the activity of the membrane potential at various locations. This would be the main notebook to direct people to (on OSBv2) where they can load the model and examine its behaviour in different scenarios. 

It should be possible to just set values for a pulse duration/width/amplitude and a dendritic input (width/time) and allow figures like this to be reproduced:

<img width="889" alt="Screenshot 2022-08-31 at 12 30 05" src="https://user-images.githubusercontent.com/1556687/187668629-750991cf-e543-4016-827d-7bd7df70be91.png">

Setting the dendritic input to zero and a longer pulse would give the standard spiking protocol as shown in the [nml readme](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/tree/master/NeuroML2). 

It wouldn't really require an interactive interface like we have for the hodgkin huxley model, but helper methods so each new protocol could be set and displayed with a new notebook cell containing something like:

```
duration_soma_pulse = '100ms'
amplitude_soma_pulse = '1nA'
amplitude_dendrite_pulse='0.1nA'
regenerate_and_run_model()
plot_model_output()
```

**Comment by pgleeson** [comment]
@shayan823 If you were happy to create something like this, it could be the last main task of the GSoC, as opposed to starting with the A1 model channels...

**Comment by shayanshafquat** [comment]
@pgleeson Okay. Will go ahead with this then. 

Regarding A1 model, as I wanted to work on it too,  will try to add something to it during and after the GSoC.

**Comment by shayanshafquat** [comment]
@pgleeson Is there a more general component type to incorporate epsp-shaped dendritic current injection i.e. `I = Iamp · (1 − e−t/2 ms) · e−t/8 ms` in the given cell? Or, do we have a define a new component type for it and include it in `*.net.nml`

**Comment by pgleeson** [comment]
Ah, I thought it was a normal synaptic input, i.e. a conductance change (with rise/decay times) resulting in an input current rather than an espc shaped current input. Where did it specifiy this? In the paper or is it in the code somewhere? 

If that's what's required then a modification of an input componet type like this would be required: https://github.com/NeuroML/NeuroML2/blob/master/NeuroML2CoreTypes/Inputs.xml#L691

**Comment by shayanshafquat** [comment]
In the paper, it was mentioned just below the figure you uploaded above.

**Comment by pgleeson** [comment]
Ok, should be possible with something like:

```
            <OnCondition test="t .geq. delay">
                <StateAssignment variable="i" value="weight * amplitude * (1 − exp(−t/tau_rise)) * exp(−t/tau_decay)"/>
            </OnCondition>
```

**Comment by shayanshafquat** [comment]
But how do we include that in the final lems file? Are we changing this inside Input.xml, adding `Inputs.xml` to the repo and then finally accessing it via `Cells.xml` ?

**Comment by pgleeson** [comment]
What I'd recommend too is to create a file (EPSC_Input.xml) with that definition, and a seperate file (EPSC_0.xml) which includes that and has the one line component instance definition (`<epspInput tauRise="2ms" ...>`), and then include the latter in the network file. Then when the parameters are reset (e.g. epsc amplitude), and you regenerate the rest of the NML, you can just regenerate the short file.

**Comment by pgleeson** [comment]
It would be something like this here: https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NeuroML2/channels/Ca/Ca.nml, but with one file for the new input `<ComponentType>` and one for the instance, which is then included in the *.net.nml and used in an `<inputList>` for the `component`

**Comment by shayanshafquat** [comment]
I am not very sure what you meant in the last statement

> and used in an `<inputList>` for the `component`?

Did you mean something like this ?

```
<inputList id="i1" component="epsp_input" population="pyr_pop">
            <input id="0" target="../hhPop1/0/pyrcell" destination="tuft"/>
        </inputList>
```

**Comment by pgleeson** [comment]
Yes if `epsp_input` was the id of the new component instance

It would need to be something like this though:
```      
 <input id="0" target="../hhPop1/0/pyrcell" segmentId="22" fractionAlong="0.5" destination="synapses"/>
```

if segment 22 is the one you're targeting say

**Comment by shayanshafquat** [comment]
@pgleeson Have added [epsp_input.nml](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/nrn_tests/NeuroML2/epsp_input.nml) with the definition of the new component type and [epsp_tuft.nml](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/nrn_tests/NeuroML2/epsp_tuft.nml) for the instance. [This is](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/df8ce74ad8c059f6600e78058db8a0172cec0991/NeuroML2/multicomp_cell.py#L592) how I have included them in the `*.net.nml`.

I tried to replicate what is there in the paper [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/nrn_tests/NeuroML2/interactive_nml.ipynb). Currently I have to change the dendritic current amplitude for each case in the `epsp_tuft.nml`. How do we regenerate this short file every time the parameters (epsp amplitude) get changed?

Other than that, when just injecting dendritic current (above threshold) with a somatic pulse to be zero as shown in the last figure in the above plot has two spikes, whereas the one inside `part (e)` [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/nrn_tests/NeuroML2/interactive_nml.ipynb) has three spikes. Though the shape looks similar. 
Also in the paper, I see no mention of where the dendritic current is being injected. Using the segment id of the last segment of the tuft for the input as it gives similar plots to the one in the paper.

**Comment by pgleeson** [comment]
> @pgleeson Have added [epsp_input.nml](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/nrn_tests/NeuroML2/epsp_input.nml) with the definition of the new component type and [epsp_tuft.nml](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/nrn_tests/NeuroML2/epsp_tuft.nml) for the instance. [This is](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/df8ce74ad8c059f6600e78058db8a0172cec0991/NeuroML2/multicomp_cell.py#L592) how I have included them in the `*.net.nml`.

Looks good. But the files should be xml, not nml, as they're not valid NeuroML files. Also root element should be `<Lems>`, see https://github.com/NeuroML/NeuroML2/blob/master/NeuroML2CoreTypes/Cells.xml. No need for an instance inside the epsp_input.nml file, just the short component definition file.

> 
> I tried to replicate what is there in the paper [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/nrn_tests/NeuroML2/interactive_nml.ipynb). Currently I have to change the dendritic current amplitude for each case in the `epsp_tuft.nml`. How do we regenerate this short file every time the parameters (epsp amplitude) get changed?

Simplest is to just generate the string for writing to a text file from the parameters currently in memory, i.e. no need to use libnml/pylems....

**Comment by shayanshafquat** [comment]
@pgleeson  But naming them to XML and then including them to network as [here](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/df8ce74ad8c059f6600e78058db8a0172cec0991/NeuroML2/multicomp_cell.py#L581) throws an error 

> epsp_tuft.xml does not appear to be a NeuroML Document. NeuroML documents must be contained in a <neuroml> tag.

That is why I tried with *.nml files

**Comment by sanjayankur31** [comment]
Hrm, the error stems from here:

https://github.com/NeuralEnsemble/libNeuroML/blob/master/neuroml/loaders.py#L32

So, you're defining a new LEMS ComponentType (class) here, so you call it `...xml` and include it in the LEMS Simulation, not the neuroml document. (That's how all the NeuroML standard ComponentType definitions are also included). 

See:

https://pyneuroml.readthedocs.io/en/development/pyneuroml.lems.html#pyneuroml.lems.LEMSSimulation.LEMSSimulation.include_lems_file

Does that make sense?

**Comment by shayanshafquat** [comment]
Yes, that helps. Thanks for that.
