### ISSUE TITLE
Check overlap in channels with other pyramidal cell models

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell#5]
There are numerous other cortical pyramidal cell models on OSB which have been converted to NeuroML, and may have the same or similar mod files, which will ease conversion of those used in this model.

- https://github.com/OpenSourceBrain/korngreen-pyramidal
Same k_slow?

- https://github.com/OpenSourceBrain/SmithEtAl2013-L23DendriticSpikes
- https://github.com/OpenSourceBrain/L5bPyrCellHayEtAl2011
- https://github.com/OpenSourceBrain/Thalamocortical

FYI @shayan823

**Comment by shayanshafquat** [comment]
Yes, it has the same k_slow. The link https://github.com/NeuroML/NeuroML2/blob/master/LEMSexamples/LEMS_NML2_Ex24_FractionalConductance.xml helped me to convert that.

**Comment by shayanshafquat** [comment]
Just wanted to check about the mod files named Slowca, kca, cad in the NEURON directory. Do we also need to convert them? @pgleeson

**Comment by pgleeson** [comment]
Yes... unfortunatley. They are inserted in the tuft of the cell, but not the soma: https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/master/NEURON/reduced_model.hoc#L69.

Calcium channels/pools and Ca dependent K channels are messy... See here though for pointers to examples in NML: https://github.com/NeuroML/NeuroML2/issues/117. For those, look at the original mod files and see if cad.mod etc. is close to what's in this repo.

**Comment by shayanshafquat** [comment]
In this nml file for cad we see a mention of gamma https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/95f1c24b666b8ce30edd5f9d73221845b9e8667f/CellTypesDatabase/models/NeuroML2/CaDynamics.nml#L11.

How do we set gamma for our cad.mod as i see no mention of it in the mod? i.e. https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/master/NEURON/channels/cad.mod

**Comment by pgleeson** [comment]
In the other file  "gamma = 0.05 : percent of free calcium". In this one all Ca is assumed/used/changing so gamma=1, or even better, no need for any gamma parameter.

**Comment by shayanshafquat** [comment]
I have created this [file](https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/issue_13_test/NeuroML2/cad.channel.nml) for ca dynamics mod file taking reference from [a similar AllenInstituteNeuroML file](https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/95f1c24b666b8ce30edd5f9d73221845b9e8667f/CellTypesDatabase/models/NeuroML2/CaDynamics.nml#L11). But it's failing to validate. 

Please help me comprehend what I am missing here. @pgleeson

**Comment by pgleeson** [comment]
@shayan823 Since the ca mechanism is a custom one, defined in a local ComponentType, it is unknown to the NeuroML schema, therefore the minCai in here: `<concentrationModel id="cad" type="concentrationModelBahl" minCai="100e-6 mM"... ` renders it invalid. 

So it's fine not to validate this file. All you need to do is rename it to cad.nml, and update the validate test to this form: https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/master/CellTypesDatabase/models/NeuroML2/.test.validate.omt
